assets:
  js_prod:
    - bundles/itkaarhusdata/assets/build/itkaarhusdata.min.js

modules:
  itkDataModule:
    files:
      - bundles/itkaarhusdata/apps/itkDataModule/itkDataSourcePicker.js

apps:
  ikApp:
    dependencies:
      - itkDataModule
